services:

  control_node:
    container_name: control_node
    build:
      context: ./control_node
      args:
        SSH_USER_PASSWORD: ${SSH_USER_PASSWORD}
        ANSIBLE_VAULT_PASSWORD: ${ANSIBLE_VAULT_PASSWORD}
    tty: true
    volumes:
      - ./control_node/ansible.cfg:/etc/ansible/ansible.cfg
      - ./control_node/ansible_key:/home/ansible/.ssh/id_rsa:ro
      - ./control_node/inventory.yml:/etc/ansible/hosts:ro
      - ./playbooks:/home/ansible/playbooks:ro

  server_0:
    container_name: server_0
    build:
      context: ./server
      args:
        SSH_USER_PASSWORD: ${SSH_USER_PASSWORD}
    tty: true
    volumes:
      - ./control_node/ansible_key.pub:/home/ansible/.ssh/authorized_keys:ro

  server_1:
    container_name: server_1
    build:
      context: ./server
      args:
        SSH_USER_PASSWORD: ${SSH_USER_PASSWORD}
    tty: true
    volumes:
      - ./control_node/ansible_key.pub:/home/ansible/.ssh/authorized_keys:ro

  server_2:
    container_name: server_2
    build:
      context: ./server
      args:
        SSH_USER_PASSWORD: ${SSH_USER_PASSWORD}
    tty: true
    volumes:
      - ./control_node/ansible_key.pub:/home/ansible/.ssh/authorized_keys:ro
