services:

  control_node:
    container_name: control_node
    build:
      context: ./control_node
    tty: true
    volumes:
      - ./control_node/ansible.cfg:/etc/ansible/ansible.cfg

  server_0:
    container_name: server_0
    build:
      context: ./server
    tty: true

  server_1:
    container_name: server_1
    build:
      context: ./server
    tty: true

  server_2:
    container_name: server_2
    build:
      context: ./server
    tty: true
