services:

  control_node:
    build:
      context: ./control_node

  server_0:
    build:
      context: ./server

  server_1:
    build:
      context: ./server

  server_2:
    build:
      context: ./server
