FROM python:3.13-slim

ARG SSH_USER_PASSWORD

# install required packages
RUN apt-get update && \
    apt-get install -y openssh-server && \
    apt-get install -y sudo && \
    rm -rf /var/lib/apt/lists/*

# add and configure ansible user
RUN useradd -ms /bin/bash ansible && \
    echo "ansible:${SSH_USER_PASSWORD}" | chpasswd && \
    usermod -aG sudo ansible

# configure ssh
RUN mkdir -p /home/ansible/.ssh && \
    chown ansible:ansible /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh

# port for ssh and start sshd
EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
