- name: create user
  tags: always
  user:
    name: "{{ username }}"
    groups: root
    
- name: add ssh key for user
  tags: always
  authorized_key:
    user: "{{ username }}"
    key: "{{ lookup('file', '/home/ansible/.ssh/authorized_keys') }}"

- name: add sudoers file for user
  tags: always
  copy:
    src: sudoer_file
    dest: "/etc/sudoers.d/{{ username }}"
    owner: root
    group: root
    mode: 0440

- name: generate sshd_config file from template
  tags: ssh
  template:
    src: "{{ ssh_template_file }}"
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: 0644
  notify: restart_sshd
