- hosts: all
  become: true
  vars_files:
    - /home/ansible/vault.yml
  tasks:

  - name: install apache and php for Debian-based systems
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: install apache and php for RedHat-based systems
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution in ["Fedora", "CentOS"]
