- hosts: all
  become: true
  vars_files:
    - /home/ansible/vault.yml
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: remove php support for apache
    apt:
      name: libapache2-mod-php
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: update repository index
    dnf:
      update_cache: yes
    when: ansible_distribution in ["Fedora", "CentOS"]

  - name: remove httpd package
    dnf:
      name: httpd
      state: absent
    when: ansible_distribution in ["Fedora", "CentOS"]

  - name: remove php support for httpd
    dnf:
      name: php
      state: absent
    when: ansible_distribution in ["Fedora", "CentOS"]