- hosts: all
  become: true
  vars_files:
    - /home/ansible/vault.yml
  pre_tasks:
    - name: install updates (Fedora)
      tags: always
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: install updates (Debian)
      tags: always
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: all
  become: true
  vars:
    username: "john_doe"
  vars_files:
    - /home/ansible/vault.yml
  roles:
    - base

- hosts: workstations
  become: true
  vars_files:
    - /home/ansible/vault.yml
  roles:
    - workstations

- hosts: web_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  roles:
    - web_servers

- hosts: db_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  roles:
    - db_servers

- hosts: file_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  roles:
    - file_servers
