- hosts: all
  become: true
  vars_files:
    - /home/ansible/vault.yml
  pre_tasks:
    - name: install updates (Fedora)
      dnf:
        update_cache: yes
        update_only: yes
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: install updates (Debian)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: web_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  tasks:
    - name: install apache and php (Debian)
      apt:
        name:
          - apache2
          - libapache2-mod-php
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: install apache and php (Fedora)
      dnf:
        name:
          - httpd
          - php
        state: latest
      when: ansible_distribution in ["Fedora", "CentOS"]

- hosts: db_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  tasks:
    - name: install mariadb (Fedora)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution in ["Fedora", "CentOS"]

    - name: install mariadb (Debian)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution in ["Debian", "Ubuntu"]

- hosts: file_servers
  become: true
  vars_files:
    - /home/ansible/vault.yml
  tasks:
    - name: install samba
      package:
        name: samba
        state: latest
